import esbuild from "esbuild";
import process from "process";
import { createRequire } from "module";
import wasmPlugin from "./wasmPlugin.mjs";
import nodeModuleShim, { nodeBuiltinExternals } from "./nodeModuleShim.mjs";
import svgrPlugin from "./svgrPlugin.mjs";

// CommonJS plugin loaded via createRequire — pure JS, no ESM export needed.
const patchRendererUnsafeUnref = createRequire(import.meta.url)(
  "./scripts/patchRendererUnsafeUnref.js"
);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// Polyfill for import.meta in CommonJS context
if (typeof import_meta === 'undefined') {
  var import_meta = {
    url: typeof __filename !== 'undefined' ? 'file://' + __filename : 'file:///obsidian-plugin'
  };
}

// Minimal \`process\` shim so the bundle survives MODULE EVALUATION on Obsidian
// mobile, whose WebView has no Node \`process\` global. Desktop-only code (Agent
// Mode) is statically imported and therefore evaluated on every platform; many
// of those modules — and bundled Node deps — read \`process.platform\`/\`.env\` at
// module scope, which throws "Can't find variable: process" on mobile and kills
// the whole plugin at load. On desktop (Electron) \`globalThis.process\` exists
// and is used as-is, so this only stubs mobile, where those code paths never run.
var process = globalThis.process || {
  env: {},
  platform: '',
  arch: '',
  argv: [],
  version: '',
  versions: {},
  cwd: function () { return '/'; },
  nextTick: function (cb) { Promise.resolve().then(cb); },
  on: function () {},
  off: function () {},
  once: function () {},
  emit: function () { return false; },
};
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeBuiltinExternals,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [nodeModuleShim, svgrPlugin, wasmPlugin, patchRendererUnsafeUnref],
  define: {
    global: "window",
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
    "import.meta.url": "import_meta.url",
  },
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
