import { colorOpacityPlugin } from "./src/lib/plugins/colorOpacityPlugin";
import colors from "tailwindcss/colors";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import("tailwindcss").Config} */
module.exports = {
  prefix: "tw-",
  content: ["./src/**/*.{js,ts,jsx,tsx}", "./src/styles/tailwind.css"],
  darkMode: ["class"],
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("tailwindcss-animate"), colorOpacityPlugin, containerQueries],
  corePlugins: {
    preflight: false,
  },
  theme: {
    textColor: {
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      normal: "var(--text-normal)",
      muted: "var(--text-muted)",
      faint: "var(--text-faint)",
      "on-accent": "var(--text-on-accent)",
      "on-accent-inverted": "var(--text-on-accent-inverted)",
      success: "var(--text-success)",
      warning: "var(--text-warning)",
      loading: "var(--color-blue)",
      error: "var(--text-error)",
      accent: "var(--text-accent)",
      "accent-hover": "var(--text-accent-hover)",
      selection: "var(--text-selection)",
      "highlight-bg": "var(--text-highlight-bg)",
      callout: {
        warning: "rgba(var(--callout-warning),<alpha-value>)",
      },
      "model-capabilities": {
        green: "var(--color-green)",
        blue: "var(--color-blue)",
      },
      "context-manager": {
        blue: "var(--color-blue)",
        green: "var(--color-green)",
        red: "var(--color-red)",
        yellow: "var(--color-yellow)",
        orange: "var(--color-orange)",
        purple: "var(--color-purple)",
        cyan: "var(--color-cyan)",
      },
      project: {
        red: "var(--color-red)",
        orange: "var(--color-orange)",
        yellow: "var(--color-yellow)",
        green: "var(--color-green)",
        blue: "var(--color-blue)",
        purple: "var(--color-purple)",
      },
    },
    backgroundColor: {
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      primary: "var(--background-primary)",
      "primary-alt": "var(--background-primary-alt)",
      secondary: "var(--background-secondary)",
      "secondary-alt": "var(--background-secondary-alt)",
      success: "rgba(var(--color-green-rgb),0.2)",
      warning: "var(--text-warning)",
      error: "rgba(var(--color-red-rgb),0.2)",
      project: {
        red: "rgba(var(--color-red-rgb),0.16)",
        orange: "rgba(var(--color-orange-rgb),0.16)",
        yellow: "rgba(var(--color-yellow-rgb),0.16)",
        green: "rgba(var(--color-green-rgb),0.16)",
        blue: "rgba(var(--color-blue-rgb),0.16)",
        purple: "rgba(var(--color-purple-rgb),0.16)",
      },
      modifier: {
        hover: "var(--background-modifier-hover)",
        "active-hover": "var(--background-modifier-active-hover)",

        error: "var(--background-modifier-error)",
        "error-rgb": "rgba(var(--background-modifier-error-rgb),<alpha-value>)",
        "error-hover": "var(--background-modifier-error-hover)",
        success: "var(--background-modifier-success)",
        "success-rgb": "rgba(var(--background-modifier-success-rgb),<alpha-value>)",
        message: "var(--background-modifier-message)",
        "form-field": "var(--background-form-field)",
      },
      interactive: {
        normal: "var(--interactive-normal)",
        hover: "var(--interactive-hover)",
        accent: "var(--interactive-accent)",
        "accent-hsl": "hsl(var(--interactive-accent-hsl),<alpha-value>)",
        "accent-hover": "var(--interactive-accent-hover)",
      },
      dropdown: {
        DEFAULT: "var(--dropdown-background)",
        blend: "var(--dropdown-background-blend-mode)",
        hover: "var(--dropdown-background-hover)",
      },
      callout: {
        warning: "rgba(var(--callout-warning),<alpha-value>)",
      },
      overlay: {
        DEFAULT: "#000",
      },
      toggle: {
        thumb: "var(--toggle-thumb-color)",
      },
    },
    borderColor: {
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      border: "var(--background-modifier-border)",
      "border-hover": "var(--background-modifier-border-hover)",
      "border-focus": "var(--background-modifier-border-focus)",
      "interactive-accent": "var(--interactive-accent)",
      error: "var(--text-error)",
    },
    ringColor: {
      ring: "var(--interactive-accent)",
    },
    ringOffsetColor: {
      ring: "var(--interactive-accent)",
    },

    colors: {
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,

      base: {
        "00": "var(--color-base-00)",
        "05": "var(--color-base-05)",
        10: "var(--color-base-10)",
        20: "var(--color-base-20)",
        25: "var(--color-base-25)",
        30: "var(--color-base-30)",
        35: "var(--color-base-35)",
        40: "var(--color-base-40)",
        50: "var(--color-base-50)",
        60: "var(--color-base-60)",
        70: "var(--color-base-70)",
        100: "var(--color-base-100)",
      },
      red: "var(--color-red)",
      "red-rgb": "rgba(var(--color-red-rgb),<alpha-value>)",
      orange: "var(--color-orange)",
      "orange-rgb": "rgba(var(--color-orange-rgb),<alpha-value>)",
      yellow: "var(--color-yellow)",
      "yellow-rgb": "rgba(var(--color-yellow-rgb),<alpha-value>)",
      green: "var(--color-green)",
      "green-rgb": "rgba(var(--color-green-rgb),<alpha-value>)",
      cyan: "var(--color-cyan)",
      "cyan-rgb": "rgba(var(--color-cyan-rgb),<alpha-value>)",
      blue: "var(--color-blue)",
      "blue-rgb": "rgba(var(--color-blue-rgb),<alpha-value>)",
      purple: "var(--color-purple)",
      "purple-rgb": "rgba(var(--color-purple-rgb),<alpha-value>)",
      pink: "var(--color-pink)",
      "pink-rgb": "rgba(var(--color-pink-rgb),<alpha-value>)",
      gray: "var(--color-gray)",
      "mono-rgb": {
        0: "rgba(var(--mono-rgb-0),<alpha-value>)",
        100: "rgba(var(--mono-rgb-100),<alpha-value>)",
      },

      caret: "var(--caret-color)",
      icon: {
        DEFAULT: "var(--icon-color)",
        hover: "var(--icon-color-hover)",
        active: "var(--icon-color-active)",
        focused: "var(--icon-color-focused)",
      },
    },
    borderWidth: {
      0: "0px",
      DEFAULT: "var(--border-width)",
    },
    zIndex: {
      cover: "var(--layer-cover)",
      sidedock: "var(--layer-sidedock)",
      "status-bar": "var(--layer-status-bar)",
      popover: "var(--layer-popover)",
      slides: "var(--layer-slides)",
      modal: "var(--layer-modal)",
      notice: "var(--layer-notice)",
      menu: "var(--layer-menu)",
      tooltip: "var(--layer-tooltip)",
      "dragged-item": "var(--layer-dragged-item)",
    },
    fontWeight: {
      thin: "var(--font-thin)",
      extralight: "var(--font-extralight)",
      light: "var(--font-light)",
      normal: "var(--font-normal)",
      medium: "var(--font-medium)",
      semibold: "var(--font-semibold)",
      bold: "var(--font-bold)",
      extrabold: "var(--font-extrabold)",
      black: "var(--font-black)",
    },
    extend: {
      borderRadius: {
        "clickable-icon": "var(--clickable-icon-radius)",
        xl: "var(--radius-xl)",
        lg: "var(--radius-l)",
        md: "var(--radius-m)",
        sm: "var(--radius-s)",
      },
      spacing: {
        0.5: "calc(var(--size-4-1) / 2)",
        1: "var(--size-4-1)",
        1.5: "calc(var(--size-4-1) * 1.5)",
        2: "var(--size-4-2)",
        3: "var(--size-4-3)",
        4: "var(--size-4-4)",
        5: "var(--size-4-5)",
        5.5: "calc(var(--size-4-5) + 2px)",
        6: "var(--size-4-6)",
      },
      cursor: {
        DEFAULT: "var(--cursor)",
        auto: "var(--cursor)",
        pointer: "var(--cursor-link)",
      },
      fontSize: {
        text: "var(--font-text-size)",
        smallest: "var(--font-smallest)",
        smaller: "var(--font-smaller)",
        small: "var(--font-small)",
        "ui-smaller": "var(--font-ui-smaller)",
        "ui-small": "var(--font-ui-small)",
        "ui-medium": "var(--font-ui-medium)",
        "ui-larger": "var(--font-ui-large, var(--font-ui-larger, 20px))",
        "ui-title": "var(--font-ui-large, var(--font-ui-larger, 20px))",
      },
      strokeWidth: {
        icon: "var(--icon-stroke)",
        "icon-xs": "var(--icon-xs-stroke-width)",
        "icon-s": "var(--icon-s-stroke-width)",
        "icon-m": "var(--icon-m-stroke-width)",
        "icon-l": "var(--icon-l-stroke-width)",
        "icon-xl": "var(--icon-xl-stroke-width)",
      },
      lineHeight: {
        normal: "var(--line-height-normal)",
        tight: "var(--line-height-tight)",
      },
      size: {
        icon: "var(--icon-size)",
        "icon-xs": "var(--icon-xs)",
        "icon-s": "var(--icon-s)",
        "icon-m": "var(--icon-m)",
        "icon-l": "var(--icon-l)",
        "icon-xl": "var(--icon-xl)",
        checkbox: "var(--checkbox-size)",
      },
      opacity: {
        icon: "var(--icon-opacity)",
        "icon-hover": "var(--icon-opacity-hover)",
        "icon-active": "var(--icon-opacity-active)",
      },
    },
  },
};
