export interface AsrSettings {
  Asr_apiKey: string;
  Asr_apiUrl: string;
  Asr_debugMode: boolean;
  Asr_encode: boolean;
  Asr_prompt: string;
  Asr_language: string;
  Asr_lineSpacing: string;
  Asr_createNewFileAfterRecording: boolean;
  Asr_createNewFileAfterRecordingPath: string;
  Asr_saveAudioFile: boolean;
  Asr_saveAudioFilePath: string;
  Asr_useLocalService: boolean;
  Asr_localServiceUrl: string;
  Asr_translate: boolean;
  Asr_transcriptionEngine: string;
  Asr_timestamps: boolean;
  Asr_timestampFormat: string;
  Asr_timestampInterval: string; // easier to store as a string and convert to number when needed
  Asr_wordTimestamps: boolean;
  Asr_vadFilter: boolean;
}
export const DEFAULT_SETTINGS: AsrSettings = {
  Asr_apiKey: "",
  Asr_apiUrl: "https://api.openai.com/v1/audio/transcriptions",
  Asr_debugMode: false,
  Asr_encode: true,
  Asr_prompt: "",
  Asr_language: "en",
  Asr_lineSpacing: "multi",
  Asr_createNewFileAfterRecording: false,
  Asr_createNewFileAfterRecordingPath: "",
  Asr_saveAudioFile: false,
  Asr_saveAudioFilePath: "",
  Asr_useLocalService: true,
  Asr_localServiceUrl: "http://localhost:9000",
  Asr_translate: false,
  Asr_transcriptionEngine: "whisper_asr",
  Asr_timestamps: false,
  Asr_timestampFormat: "auto",
  Asr_timestampInterval: "0", // easier to store as a string and convert to number when needed
  Asr_wordTimestamps: false,
  Asr_vadFilter: false, // this doesn't seem to do anything in the current version of the Whisper ASR server
};
export const LANGUAGES = {
  AFRIKAANS: "af",
  ALBANIAN: "sq",
  AMHARIC: "am",
  ARABIC: "ar",
  ARMENIAN: "hy",
  ASSAMESE: "as",
  AZERBAIJANI: "az",
  BASHKIR: "ba",
  BASQUE: "eu",
  BELARUSIAN: "be",
  BENGALI: "bn",
  BOSNIAN: "bs",
  BRETON: "br",
  BULGARIAN: "bg",
  BURMESE: "my",
  CATALAN: "ca",
  CHINESE: "zh",
  CROATIAN: "hr",
  CZECH: "cs",
  DANISH: "da",
  DUTCH: "nl",
  ENGLISH: "en",
  ESTONIAN: "et",
  FAROESE: "fo",
  FINNISH: "fi",
  FRENCH: "fr",
  GALICIAN: "gl",
  GEORGIAN: "ka",
  GERMAN: "de",
  GREEK: "el",
  GUJARATI: "gu",
  HAITIAN: "ht",
  HAUSA: "ha",
  HEBREW: "he",
  HINDI: "hi",
  HUNGARIAN: "hu",
  ICELANDIC: "is",
  INDONESIAN: "id",
  ITALIAN: "it",
  JAPANESE: "ja",
  JAVANESE: "jv",
  KANNADA: "kn",
  KAZAKH: "kk",
  KOREAN: "ko",
  LAO: "lo",
  LATIN: "la",
  LATVIAN: "lv",
  LINGALA: "ln",
  LITHUANIAN: "lt",
  LUXEMBOURGISH: "lb",
  MACEDONIAN: "mk",
  MALAGASY: "mg",
  MALAY: "ms",
  MALAYALAM: "ml",
  MALTESE: "mt",
  MAORI: "mi",
  MARATHI: "mr",
  MONGOLIAN: "mn",
  NEPALI: "ne",
  NORWEGIAN: "no",
  OCCITAN: "oc",
  PANJABI: "pa",
  PERSIAN: "fa",
  POLISH: "pl",
  PORTUGUESE: "pt",
  PUSHTO: "ps",
  ROMANIAN: "ro",
  RUSSIAN: "ru",
  SANSKRIT: "sa",
  SERBIAN: "sr",
  SHONA: "sn",
  SINDHI: "sd",
  SINHALA: "si",
  SLOVAK: "sk",
  SLOVENIAN: "sl",
  SOMALI: "so",
  SPANISH: "es",
  SUNDANESE: "su",
  SWAHILI: "sw",
  SWEDISH: "sv",
  TAGALOG: "tl",
  TAJIK: "tg",
  TAMIL: "ta",
  TATAR: "tt",
  TELUGU: "te",
  THAI: "th",
};
